teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 10.0
    scale_linear_turbo:
      x: 15.0

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 55.0

    require_enable_button: true
    enable_button: 4  # L2 shoulder button
    enable_turbo_button: 5  # L1 shoulder button
