<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot" >

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI"          value="3.1415926535897931"/>
  <xacro:property name="base_mass"   value="1.0" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width"  value="0.50" />
  <xacro:property name="base_length" value="0.44" />
  <xacro:property name="base_height" value="0.04" />
  <xacro:property name="wheel_mass"  value="1.50" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len"   value="0.050" />
  <xacro:property name="wheel_radius" value="0.085" />
  <xacro:property name="wheel_x_offset" value="0.150" />
  <xacro:property name="wheel_z_offset" value="0.040" />
  <xacro:property name="caster_wheel_mass" value="0.1" /> <!-- arbitrary value for caster wheel mass -->
  <xacro:property name="caster_wheel_radius" value="0.025" />
  <xacro:property name="caster_x_offset" value="-0.150" />
  <xacro:property name="caster_z_offset" value="-0.010" />

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </xacro:macro>

	<material name="white">
   		<color rgba="0.8 0.8 0.8 1"/>
   	</material>

	<material name="black">
   		<color rgba="0.1 0.1 0.1 1"/>
   	</material>

  <!-- ****************** ROBOT BASE FOOTPRINT ***************************  -->
  <link name="world"/>

  <joint name="worl_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <!-- ********************** ROBOT BASE *********************************  -->
  <!-- Base Link -->
  <link name="base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_length*base_length)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
	</link>

  <!-- ****************** ROBOT BASE FOOTPRINT ***************************  -->
  <link name="base_footprint"/>
  
  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 ${wheel_z_offset-wheel_radius}" rpy="0 0 0"/>
  </joint>


    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_wheel"/>
      <origin xyz="${wheel_x_offset} ${wheel_len/2+base_width/2} ${wheel_z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- left wheel Link -->
    <link name="left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_len}" />
      </inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_wheel"/>
      <origin xyz="${wheel_x_offset} ${-wheel_len/2-base_width/2} ${wheel_z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- right wheel Link -->
    <link name="right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_len}" />
      </inertial>
    </link>

    <joint name="caster_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_wheel"/>
      <origin xyz="${caster_x_offset} 0 ${caster_z_offset}" rpy="0 0 0"/>
    </joint>

    <!-- caster wheel Link -->
    <link name="caster_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
      </link>

    <joint name="laser_joint" type="fixed">
      <parent link="base_link"/>
      <child link="laser"/>
      <origin xyz="-0.200 0.0 0.320 " rpy="0 0 0"/>
    </joint>

    <!-- caster left wheel Link -->
    <link name="laser">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	        <box size="0.040 0.040 0.080"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
		<box size="0.040 0.040 0.080"/>
        </geometry>
        <material name="black"/>
      </visual>

      </link>

</robot>
